OLED_ENABLE = yes
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
LTO_ENABLE = yes
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no
MAGIC_ENABLE = no
MUSIC_ENABLE = no
RGBLIGHT_ENABLE = no
RGB_MATRIX_ENABLE = yes

AVR_USE_MINIMAL_PRINTF = yes
